---
- hosts: all
  become: true
  tasks:
  - name: Install Docker dependencies
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2

  - name: Add Docker YUM repository
    shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

  - name: Install Docker
    yum:
      name: docker-ce
      state: present

  - name: Start Docker and enable on boot
    systemd:
      name: docker
      state: started
      enabled: yes
